create table payment (
  id int generated by default as identity (start with 1) primary key,
  amount DOUBLE,
  debtorIban varchar(50),
  creditorIban varchar(50),
  type varchar(100),
  currency varchar(50),
  creationDate date,
  active boolean not null,
  fee DOUBLE,
  details varchar(50)
);